---
title: "Causal Inference Analysis - LLCM T1"
output: html_notebook
---

#### to view the knitted HTML in github, use the following url
https://htmlpreview.github.io/?https://github.com/wandajuan-houzz/casual-impact/blob/master/llcm-t1.nb.html


#### Test ON: 2021-10-22 ~ 2021-12-09



```{r echo = T, message = FALSE}
library(CausalImpact)
library(zoo)
```

```{r}
##########################################################
# Experiment overall analysis
##########################################################

####### T1 ######
###### GMV ###### 
gmv_t1 <- read.csv("~/Google Drive/202109 listing level target:floor margin/casual impact/weekly_pv_gmv_t1_1209.csv", sep = ',',header = TRUE)
gmv_t1 <- gmv_t1[order(gmv_t1$period, decreasing=TRUE), ]
gmv_t1 <- gmv_t1[order(gmv_t1$week), ]
#head(gmv_t1)
#dim(gmv_t1)

# Construct control and test gmv_t1
gmv_t1[,1] <- as.Date(gmv_t1[,1],  format="%Y-%m-%d")

# Define date 
times=as.Date(gmv_t1[,1])
pre.period <- c(min(which(gmv_t1$period=='pre')), max(which(gmv_t1$period=='pre')))
post.period <- c(min(which(gmv_t1$period=='post')), max(which(gmv_t1$period=='post')))


X = gmv_t1[, c(3:8, 10)]
y = gmv_t1[, 9]
# gmv_t1 is (test, control, date)
fit_gmv_t1=zoo(cbind(y, X),times)
# Model fit
impact <- CausalImpact(fit_gmv_t1,times[pre.period] , times[post.period])
summary(impact)
summary(impact, "report")
plot(impact)
```

```{r}
####### T1 ######
####### CM #####
cm_t1 <- read.csv("~/Google Drive/202109 listing level target:floor margin/casual impact/weekly_pv_cm_t1_1209.csv", sep = ',',header = TRUE)
cm_t1 <- cm_t1[order(cm_t1$period, decreasing=TRUE), ]
cm_t1 <- cm_t1[order(cm_t1$week), ]
#head(cm_t1)
#dim(cm_t1)

# Construct control and test cm_t1
cm_t1[,1] <- as.Date(cm_t1[,1],  format="%Y-%m-%d")
head(cm_t1)

# Define date 
times=as.Date(cm_t1[,1])
pre.period <- c(min(which(cm_t1$period=='pre')), max(which(cm_t1$period=='pre')))
post.period <- c(min(which(cm_t1$period=='post')), max(which(cm_t1$period=='post')))


X = cm_t1[, c(3:8, 10)]
y = cm_t1[, 9]
# cm_t1 is (test, control, date)
fit_cm_t1=zoo(cbind(y, X),times)
# Model fit
impact <- CausalImpact(fit_cm_t1,times[pre.period] , times[post.period])

summary(impact)
summary(impact, "report")
plot(impact)
```